import pandas as pd
import os

def merge_outputs_case_base():

    # 1. Define paths relative to the src/ directory
    base_dir = os.path.dirname(os.path.abspath(__file__))
    processed_csv = os.path.join(base_dir, '../data/processed/checkpoint_case_base.csv')
    raw_csv = os.path.join(base_dir, '../data/raw/raw_case_outputs.csv')
    output_csv = os.path.join(base_dir, '../data/processed/checkpoint_case_base_copy.csv')

    # 2. Load the CSVs, enforcing string type for IDs to preserve leading zeros
    try:
        df_base = pd.read_csv(processed_csv, dtype={'id': str})
        df_raw = pd.read_csv(raw_csv, dtype={'case_id': str})
    except FileNotFoundError as e:
        print(f"Error loading files: {e}")
        return

    # 3. Pivot the raw outputs dataframe
    # This transforms the 'model' rows into columns containing their respective 'insight' values
    df_pivot = df_raw.pivot(index='case_id', columns='model', values='insight').reset_index()

    # 4. Rename the columns to match your exact requested format
    rename_mapping = {
        'Qwen-3-VL-8B': 'qwen_insight',
        'Pixtral-12B': 'pixtral_insight',
        'Idefics3-8B': 'idefics_insight'
    }
    df_pivot = df_pivot.rename(columns=rename_mapping)

    # Ensure only the required columns are kept for the merge (dropping 'error' or unexpected models)
    columns_to_keep = ['case_id'] + [col for col in rename_mapping.values() if col in df_pivot.columns]
    df_pivot = df_pivot[columns_to_keep]

    # 5. Merge the pivoted data into the base dataframe
    # Using a left merge ensures we keep all original rows from checkpoint_case_base.csv
    df_merged = pd.merge(df_base, df_pivot, left_on='id', right_on='case_id', how='left')

    # Drop the duplicate 'case_id' column generated by the merge
    if 'case_id' in df_merged.columns:
        df_merged = df_merged.drop(columns=['case_id'])

    # 6. Save to a new copy, leaving the original intact
    df_merged.to_csv(output_csv, index=False)
    print(f"Successfully created {output_csv} with the new insight columns appended.")

if __name__ == "__main__":
    merge_outputs_case_base()